apiVersion: 1

datasources:
  - name: PostgreSQL
    type: postgres
    access: proxy
    url: ${DB_HOST}:5432
    database: ${GRAFANA_DB_NAME}
    user: ${DB_USERNAME}
    secureJsonData:
      password: ${DB_PASSWORD}
    jsonData:
      sslmode: 'disable'
      database: ${GRAFANA_DB_NAME}