# config file version
apiVersion: 1

# list of datasources to insert/update
# available in the database
datasources:
  - name: PostgreSQL
    type: postgres
    access: proxy
    url: <INTERNAL_IP_ADRESS_OF_DB_INSTANCE>:5432 # use the following if local: postgres:5432
    database: churn
    user: airflow
    secureJsonData:
      password: 'airflow'
    jsonData:
      sslmode: 'disable'
      database: churn